# Generated by Django 2.2.5 on 2021-01-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='账户')),
                ('key', models.CharField(max_length=1000, verbose_name='key')),
                ('engine_type', models.CharField(max_length=20, verbose_name='引擎类型')),
                ('proxy', models.CharField(max_length=100, null=True, verbose_name='代理')),
            ],
            options={
                'db_table': 'search_engine',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名称')),
                ('password', models.CharField(max_length=100, verbose_name='用户密码')),
                ('user_permission', models.IntegerField(verbose_name='用户权限')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.BigIntegerField(verbose_name='手机号码')),
                ('task_count', models.IntegerField(default=0, verbose_name='任务数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
                'db_table': 'user_info',
            },
        ),
    ]
