# Generated by Django 2.2.5 on 2021-01-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210106_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, verbose_name='账户')),
                ('key', models.CharField(max_length=1000, verbose_name='key')),
                ('engine_type', models.CharField(max_length=20, verbose_name='引擎类型')),
                ('proxy', models.CharField(max_length=100, verbose_name='代理')),
            ],
            options={
                'db_table': 'search_engine',
            },
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='engine_type',
        ),
    ]
