# Generated by Django 2.2.5 on 2021-01-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210112_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchengine',
            name='proxy',
            field=models.CharField(max_length=100, null=True, verbose_name='代理'),
        ),
    ]
