# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0002_auto_20210105_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notelog',
            name='file',
        ),
        migrations.AddField(
            model_name='notelog',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Note', verbose_name='对应笔记'),
            preserve_default=False,
        ),
    ]
