# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0003_auto_20210105_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file_dir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanage.NoteDir', verbose_name='归属目录'),
        ),
    ]
