# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-05 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0004_auto_20210105_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='file_name',
            field=models.CharField(default=1, max_length=500, verbose_name='文件名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notelog',
            name='note_name',
            field=models.CharField(default=1, max_length=500, verbose_name='笔记名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='file_dir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanage.NoteDir', verbose_name='归属目录'),
            preserve_default=False,
        ),
    ]
