# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-05 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0005_auto_20210105_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelog',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='notelog',
            name='note_name',
        ),
    ]
