# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-06 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0006_auto_20210105_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedir',
            name='pid',
            field=models.CharField(max_length=50, verbose_name='父目录id'),
        ),
        migrations.AlterField(
            model_name='filedir',
            name='sub_dir',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='子目录id'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(null=True, verbose_name='笔记内容'),
        ),
        migrations.AlterField(
            model_name='notedir',
            name='pid',
            field=models.CharField(max_length=50, verbose_name='父目录id'),
        ),
        migrations.AlterField(
            model_name='notedir',
            name='sub_dir',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='文件子目录id'),
        ),
    ]
