# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-07 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0008_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanage.NoteClasses', verbose_name='笔记标签'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='classify',
            field=models.IntegerField(default=1, verbose_name='笔记分类'),
        ),
    ]
