# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-07 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0009_auto_20210107_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteclasses',
            old_name='class_name',
            new_name='label_name',
        ),
    ]
