# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-07 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0010_auto_20210107_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteClasses',
            new_name='Label',
        ),
    ]
