# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210106_1352'),
        ('taskmanage', '0011_auto_20210107_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(default=1, max_length=1000, verbose_name='文件描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='创建用户'),
            preserve_default=False,
        ),
    ]
