# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-08 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0012_auto_20210108_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='box_check',
            field=models.CharField(max_length=100, null=True, verbose_name='沙箱检测'),
        ),
    ]
