# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-11 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0013_file_box_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task', verbose_name='对应任务'),
            preserve_default=False,
        ),
    ]
