# Generated by Django 2.2.5 on 2021-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0016_backnote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default=1, max_length=100, verbose_name='文件内容'),
            preserve_default=False,
        ),
    ]
