# Generated by Django 2.2.5 on 2021-01-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progress', models.IntegerField(default=0)),
                ('backup_filepath', models.TextField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_backup_record',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未知', max_length=128)),
                ('ip', models.CharField(max_length=128)),
                ('os_info', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': '主机表',
                'db_table': 'tb_host',
            },
        ),
        migrations.CreateModel(
            name='OperatingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('operator_id', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_operating_log',
            },
        ),
        migrations.CreateModel(
            name='ServerPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=155, null=True)),
                ('port', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_server_port',
            },
        ),
        migrations.CreateModel(
            name='TaskCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '凭证列表',
                'db_table': 'tb_task_certificate',
            },
        ),
        migrations.CreateModel(
            name='TaskPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('port', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '端口列表',
                'db_table': 'tb_task_port',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('update_time', models.DateTimeField(null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('describe', models.TextField(null=True)),
                ('level', models.IntegerField()),
                ('quote', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminq.Host')),
            ],
            options={
                'verbose_name': '任务漏洞表',
                'db_table': 'tb_task_vulnerability',
            },
        ),
    ]
