# Generated by Django 2.2.5 on 2021-01-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('adminq', '0001_initial'),
        ('mind', '0001_initial'),
        ('taskmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskvulnerability',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='taskvulnerability',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='taskport',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminq.Host'),
        ),
        migrations.AddField(
            model_name='taskport',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.MindNode'),
        ),
        migrations.AddField(
            model_name='taskport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='taskcertificate',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminq.Host'),
        ),
        migrations.AddField(
            model_name='taskcertificate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='taskcertificate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='host',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.MindNode'),
        ),
        migrations.AddField(
            model_name='host',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo'),
        ),
    ]
