# Generated by Django 2.2.5 on 2021-01-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('mind', '0001_initial'),
        ('taskmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodefile',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanage.File'),
        ),
        migrations.AddField(
            model_name='nodefile',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.MindNode'),
        ),
        migrations.AddField(
            model_name='mindonlineuser',
            name='mind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mind.MindMap'),
        ),
        migrations.AddField(
            model_name='mindonlineuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='mindnode',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.MindNode'),
        ),
        migrations.AddField(
            model_name='mindnode',
            name='mind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.MindMap'),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='mindlog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanage.Task'),
        ),
        migrations.AddField(
            model_name='mindlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户'),
        ),
    ]
