# Generated by Django 2.2.5 on 2021-01-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('mind', '0002_auto_20210125_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindNodeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=0, verbose_name='执行动作')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mind.MindMap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户')),
            ],
        ),
    ]
