# Generated by Django 2.2.5 on 2021-01-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0003_mindnodelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindnodelog',
            name='node_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
