# Generated by Django 2.2.5 on 2021-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0004_mindnodelog_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindnode',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
