# Generated by Django 2.2.5 on 2021-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0005_mindnode_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindnode',
            name='is_work',
            field=models.BooleanField(default=True),
        ),
    ]
