# Generated by Django 2.2.5 on 2021-02-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0006_mindnode_is_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindnode',
            name='is_work_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
